version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      # --- PASSWORD UPDATED HERE ---
      MONGO_INITDB_ROOT_PASSWORD: user123 
    volumes:
      - mongo-data:/data/db

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "3000:3000"
    env_file:
      - ./auth-service/.env
    depends_on:
      - mongodb

  profile-service:
    build: ./profile-service
    container_name: profile-service
    ports:
      - "3001:3001"
    env_file:
      - ./profile-service/.env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - auth-service
      - profile-service

volumes:
  mongo-data: